language: node_js
node_js:
  - "lts/*"

cache: yarn
script: yarn test && yarn build && yarn smoke-test

branches:
  only:
    - develop
    - master

webhooks:
  on_success: change  # options: [always|never|change] default: always
  on_failure: always  # options: [always|never|change] default: always
  on_start: never     # options: [always|never|change] default: always

after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
