#!/usr/bin/env sh
rm -rf docs && \
  ./node_modules/.bin/typedoc \
    --out docs \
    --includes src \
    --exclude src/helpers.ts \
    --tsconfig ts/doc.tsconfig.json \
    --theme minimal \
    src && \
  touch docs/.nojekyll && \
echo "snatvb.ru" > docs/CNAME