#!/usr/bin/env sh
rm -rf docs && \
  ./node_modules/.bin/typedoc \
    --options scripts/typedoc.js \
    --includes src \
    --theme doc-theme/bin/default \
    --tsconfig ts/doc.tsconfig.json \
    src && \
  touch docs/.nojekyll && \
echo "snatvb.ru" > docs/CNAME